# Content of pipeline.yaml
meta:
  import_tasks_from: pipeline.features.yaml

tasks:
   # source is the code you want to execute (.ipynb also supported)
  - source: src/data/make_dataset.py
    # products are task's outputs
    product:
      # scripts generate executed notebooks as outputs
      nb: output/notebooks/make_dataset.ipynb
      # you can define as many outputs as you want
      data: output/data/interim/iris.parquet

  # Feature pipeline code will execute here.

  - source: src/models/train_model.py
    product:
      nb: output/notebooks/train_model.ipynb
      model: output/models/model.pkl
