# Content of pipeline.yaml
tasks:
   # source is the code you want to execute (.ipynb also supported)
  - source: src/market_watch/data/make_dataset.py
    # products are task's outputs
    product:
      # scripts generate executed notebooks as outputs
      nb: notebooks/make_dataset.ipynb
      # you can define as many outputs as you want
      data: data/raw/iris.parquet

#  - source: src/market_watch/data/gdelt_dataset.py
#    product:
#      nb: notebooks/gdelt_dataset.ipynb
#      data: data/external/gdelt_dataset.hdf5
#
#  - source: src/market_watch/data/clean_dataset.py
#    product:
#      nb: notebooks/clean_dataset.ipynb
#      data: data/processed/clean_data.parquet

  - source: src/market_watch/features/build_features.py
    product:
      nb: notebooks/build_features.ipynb
      data: data/features/features.parquet

  - source: src/market_watch/models/train_model.py
    product:
      nb: notebooks/train_model.ipynb
      model: models/model.pkl

#  - source: src/market_watch/models/predict_model.py
#    product:
#      nb: notebooks/predict_model.ipynb
#
#  - source: src/market_watch/visualization/visualize.py
#    product:
#      nb: notebooks/visualize.ipynb