# Content of pipeline.yaml
meta:
  import_tasks_from: pipeline.features.yaml

tasks:
   # source is the code you want to execute (.ipynb also supported)
  - source: src/data/get_gdelt_data.py
    # products are task's outputs
    product:
      # scripts generate executed notebooks as outputs
      nb: output/notebooks/get_gdelt_data.ipynb
      # you can define as many outputs as you want incl a directory
      data: output/data/raw
    params:
      query_params:
        rolling_window: '{{rolling_window}}'

  - source: src/data/filter_gdelt_data.py
    product:
      nb: output/notebooks/filter_gdelt_data.ipynb
      data: output/data/interim
    params:
      cameo_codefile_urls:
        cameo_country_codes: '{{cameo_country_code_url}}'
        fips_country_codes: '{{fips_country_code_url}}'
        cameo_type_codes: '{{ cameo_type_code_url }}'
        cameo_ethnic_codes: '{{cameo_ethnic_code_url}}'
        cameo_religion_codes: '{{cameo_religion_code_url}}'
        cameo_event_codes: '{{cameo_event_code_url}}'
        cameo_goldsteinscale_mappings: '{{cameo_goldsteinscale_url}}'
      gdelt_file_urls:
        gdelt_lastupdate_url: '{{gdelt_lastupdate_url}}'
        gdelt_lastupdate_translated_url: '{{gdelt_lastupdate_translated_url}}'
        gdelt_master_url: '{{gdelt_master_url}}'
        gdelt_master_translated_url: '{{gdelt_master_translated_url}}'
      query_params:
        search_terms: '{{search_terms}}'

  # Feature pipeline code will execute here.

